version: '3'

services:
  php-apache:
    build: .
    volumes:
      - ./source:/var/www/html # Монтируем исходный код приложения
      - ./services/php/php.ini:/usr/local/etc/php/php.ini # Настройки PHP
      - ./services/apache/logs:/var/log/apache2 # Логи Apache
      - ./services/apache/config/000-default.conf:/etc/apache2/sites-available/000-default.conf # Apache конфиг
      - ./services/apache/config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf # Активация конфига Apache
      - ./services/php/logs/php_errors.log:/var/log/php_errors.log

    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./services/mysql/data:/var/lib/mysql # Данные MySQL
      - ./services/mysql/config:/etc/mysql/conf.d # Настройки MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - mysql